name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Clone repository
        run: git clone ${{ secrets.otp }}

      - name: Test
        run: |
         cd otp
         go mod init otp
         go mod tidy
         go run main.go
  
      
